
```{r}
library(tidyverse)
library(ggplot2)

athletes <- read.csv("~/Documents/R/Olympics/Olympic_Athletes/athlete_events.csv", stringsAsFactors = F)
region <- read.csv("~/Documents/R/Olympics/Olympic_Athletes/country_definitions.csv", stringsAsFactors = F)
```
```{r}
colnames(athletes)
```



```{r}
#Clean clean athlete dataset for visualisation
df_athletes <- athletes %>% 
  select(ID, Name, NOC, Year, Season) %>% 
  group_by(ID, Name) %>% 
  unique()

df_athletes
```


```{r}
#Clean region dataset
df_region <- region %>% 
  select(-notes)

df_region
```


```{r}
#Merge athletes and region
full <- left_join(df_athletes, df_region, by="NOC")

#Visualise dataset

vis <- function(data, seas = c("Summer", "Winter")){
  
  top_noc <- data %>% 
  group_by(NOC) %>% 
  summarise(TotalCount = n()) %>% 
  ungroup() %>% 
  top_n(5) %>% 
  pull(NOC)
  
  
  df <- data %>% 
    filter(NOC %in% top_noc,
           Season == seas) %>% 
    group_by(Year, NOC) %>% 
    summarise(count = n(), .groups = "keep") %>% 
    ungroup() %>% 
    group_by(NOC) %>% 
    mutate(label = ifelse(row_number() == n(), count, NA)) %>% 
    ungroup() %>% 
    arrange(Year, NOC) %>% 
    ggplot(aes(x = Year, y=count, color = NOC, label = label)) + 
    geom_line(alpha = 0.6, linewidth = 1)+
    geom_text(nudge_x = 3, size = 4)+
    labs(title = paste0("Top 5 Country Participation - ", seas, " Olympics"))+
    ylab("Number of athletes")+
    theme_bw()+
    theme(legend.position = "bottom",
          legend.title = element_blank())
  
return(df)

}
```


```{r}
#vis(full %>% filter(Season == "Winter"))
vis(full, "Winter")
```


```{r}
#vis(full %>% filter(Season == "Summer"))
vis(full, "Summer")
```

















